env:
  browser: true
  commonjs: true
  es2021: true
parser: "@typescript-eslint/parser"
extends:
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
plugins: []
rules: 
  indent: 
    - error
    - 4
